// <auto-generated />
using CreditosApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditosApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CreditosApp.Models.ProductoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComisionPct")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinMeses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tea")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductosCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
